# docker-compose build
# docker-compose run --rm app go run db/migrate.go up

version: '3'

services:
  app:
    build: ./containers/app
    working_dir: "/go/src/github.com/stobita/graphql-sample/"
    volumes:
      - '.:/go/src/github.com/stobita/graphql-sample/'
    ports:
      - '8086:8086'
    command: 'gin --port 8086 server.go'
    environment:
      PORT: 8086
      SAMPLE_DB_USER: gouser
      SAMPLE_DB_PASS: gouser
      SAMPLE_DB_HOST: db
      SAMPLE_DB_NAME: graphql_sample
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: graphql_sample
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gouser
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '4307:3306'
  minio:
    image: minio/minio
    ports:
      - "9001:9001"
    volumes:
      - s3-data:/export
    entrypoint: sh
    command: -c 'mkdir -p /export/graphql-sample && /usr/bin/minio server /export'
    environment:
      MINIO_ACCESS_KEY: sample_access_key
      MINIO_SECRET_KEY: sample_secret_key
      MINIO_REGION: sample_region
volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
