FROM golang:1.10

RUN go get github.com/gin-gonic/gin
RUN go get github.com/codegangsta/gin
RUN go get github.com/graphql-go/graphql
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/pressly/goose
RUN go get github.com/go-xorm/xorm
